Max Weight: 180

Less And Equal To:
  Percentage: 24
  SpeedPercent: 105
Between:
  Percentage: 25,49
  SpeedPercent: 95
Between1:
  Percentage: 50,100  
  SpeedPercent: 70
Bigger Than:
  Percentage: 100
  SpeedPercent: 50

ANVIL: 0
APPLE: 0
ARROW: 0
BAKED_POTATO: 0
BEACON: 0
BED: 0
BED_BLOCK: 0
BEDROCK: 0
BIRCH_WOOD_STAIRS: 0
BLAZE_POWDER: 0
BLAZE_ROD: 0
BOAT: 0
BONE: 0
BOOK: 0
BOOK_AND_QUILL: 0
BOOKSHELF: 0
BOW: 0
BOWL: 0
BREAD: 0
BREWING_STAND: 0
BREWING_STAND_ITEM: 0
BRICK: 0
BRICK_STAIRS: 0
BROWN_MUSHROOM: 0
BUCKET: 0
BURNING_FURNACE: 0
CACTUS: 0
CAKE: 0
CAKE_BLOCK: 0
CARPET: 0
CARROT: 0
CARROT_ITEM: 0
CARROT_STICK: 0
CAULDRON: 0
CAULDRON_ITEM: 0
CHAINMAIL_BOOTS: 0
CHAINMAIL_CHESTPLATE: 0
CHAINMAIL_HELMET: 0
CHAINMAIL_LEGGINGS: 0
CHEST: 0
CLAY: 0
CLAY_BALL: 0
CLAY_BRICK: 0
COAL: 0
COAL_BLOCK: 0
COAL_ORE: 0
COBBLE_WALL: 0
COBBLESTONE: 0
COBBLESTONE_STAIRS: 0
COCOA: 0
COMMAND: 0
COMPASS: 0
COOKED_BEEF: 0
COOKED_CHICKEN: 0
COOKED_FISH: 0
COOKIE: 0
CROPS: 0
DAYLIGHT_DETECTOR: 0
DEAD_BUSH: 0
DETECTOR_RAIL: 0
DIAMOND: 0
DIAMOND_AXE: 0
DIAMOND_BARDING: 0
DIAMOND_BLOCK: 0
DIAMOND_BOOTS: 0
DIAMOND_CHESTPLATE: 0
DIAMOND_HELMET: 0
DIAMOND_HOE: 0
DIAMOND_LEGGINGS: 0
DIAMOND_ORE: 0
DIAMOND_PICKAXE: 0
DIAMOND_SPADE: 0
DIAMOND_SWORD: 0
DIODE: 0
DIODE_BLOCK_OFF: 0
DIODE_BLOCK_ON: 0
DIRT: 0
DISPENSER: 0
DOUBLE_STEP: 0
DRAGON_EGG: 0
DROPPER: 0
EGG: 0
EMERALD: 0
EMERALD_BLOCK: 0
EMERALD_ORE: 0
EMPTY_MAP: 0
ENCHANTED_BOOK: 0
ENCHANTMENT_TABLE: 0
ENDER_CHEST: 0
ENDER_PEARL: 0
ENDER_PORTAL: 0
ENDER_PORTAL_FRAME: 0
ENDER_STONE: 0
EXP_BOTTLE: 0
EXPLOSIVE_MINECART: 0
EYE_OF_ENDER: 0
FEATHER: 0
FENCE: 0
FENCE_GATE: 0
FERMENTED_SPIDER_EYE: 0
FIRE: 0
FIREBALL: 0
FIREWORK: 0
FIREWORK_CHARGE: 0
FISHING_ROD: 0
FLINT: 0
FLINT_AND_STEEL: 0
FLOWER_POT: 0
FLOWER_POT_ITEM: 0
FURNACE: 0
GHAST_TEAR: 0
GLASS: 0
GLASS_BOTTLE: 0
GLOWING_REDSTONE_ORE: 0
GLOWSTONE: 0
GLOWSTONE_DUST: 0
GOLD_AXE: 0
GOLD_BARDING: 0
GOLD_BLOCK: 0
GOLD_BOOTS: 0
GOLD_CHESTPLATE: 0
GOLD_HELMET: 0
GOLD_HOE: 0
GOLD_INGOT: 0
GOLD_LEGGINGS: 0
GOLD_NUGGET: 0
GOLD_ORE: 0
GOLD_PICKAXE: 0
GOLD_PLATE: 0
GOLD_RECORD: 0
GOLD_SPADE: 0
GOLD_SWORD: 0
GOLDEN_APPLE: 0
GOLDEN_CARROT: 0
GRASS: 0
GRAVEL: 0
GREEN_RECORD: 0
GRILLED_PORK: 0
HARD_CLAY: 0
HAY_BLOCK: 0
HOPPER: 0
HOPPER_MINECART: 0
HUGE_MUSHROOM_1: 0
HUGE_MUSHROOM_2: 0
ICE: 0
INK_SACK: 0
IRON_AXE: 0
IRON_BARDING: 0
IRON_BLOCK: 0
IRON_BOOTS: 0
IRON_CHESTPLATE: 0
IRON_DOOR: 0
IRON_DOOR_BLOCK: 0
IRON_FENCE: 0
IRON_HELMET: 0
IRON_HOE: 0
IRON_INGOT: 0
IRON_LEGGINGS: 0
IRON_ORE: 0
IRON_PICKAXE: 0
IRON_PLATE: 0
IRON_SPADE: 0
IRON_SWORD: 0
ITEM_FRAME: 0
JACK_O_LANTERN: 0
JUKEBOX: 0
JUNGLE_WOOD_STAIRS: 0
LADDER: 0
LAPIS_BLOCK: 0
LAPIS_ORE: 0
LAVA: 0
LAVA_BUCKET: 0
LEASH: 0
LEATHER: 0
LEATHER_BOOTS: 0
LEATHER_CHESTPLATE: 0
LEATHER_HELMET: 0
LEATHER_LEGGINGS: 0
LEAVES: 0
LEVER: 0
LOCKED_CHEST: 0
LOG: 0
LONG_GRASS: 0
MAGMA_CREAM: 0
MAP: 0
MELON: 0
MELON_BLOCK: 0
MELON_SEEDS: 0
MELON_STEM: 0
MILK_BUCKET: 0
MINECART: 0
MOB_SPAWNER: 0
MONSTER_EGG: 0
MONSTER_EGGS: 0
MOSSY_COBBLESTONE: 0
MUSHROOM_SOUP: 0
MYCEL: 0
NAME_TAG: 0
NETHER_BRICK: 0
NETHER_BRICK_ITEM: 0
NETHER_BRICK_STAIRS: 0
NETHER_FENCE: 0
NETHER_STALK: 0
NETHER_STAR: 0
NETHER_WARTS: 0
NETHERRACK: 0
NOTE_BLOCK: 0
OBSIDIAN: 0
PAINTING: 0
PAPER: 0
PISTON_BASE: 0
PISTON_EXTENSION: 0
PISTON_MOVING_PIECE: 0
PISTON_STICKY_BASE: 0
POISONOUS_POTATO: 0
PORK: 0
PORTAL: 0
POTATO: 0
POTATO_ITEM: 0
POTION: 0
POWERED_MINECART: 0
POWERED_RAIL: 0
PUMPKIN: 0
PUMPKIN_PIE: 0
PUMPKIN_SEEDS: 0
PUMPKIN_STEM: 0
QUARTZ: 0
QUARTZ_BLOCK: 0
QUARTZ_ORE: 0
QUARTZ_STAIRS: 0
RAILS: 0
RAW_BEEF: 0
RAW_CHICKEN: 0
RAW_FISH: 0
RECORD_10: 0
RECORD_11: 0
RECORD_12: 0
RECORD_3: 0
RECORD_4: 0
RECORD_5: 0
RECORD_6: 0
RECORD_7: 0
RECORD_8: 0
RECORD_9: 0
RED_MUSHROOM: 0
RED_ROSE: 0
REDSTONE: 0
REDSTONE_BLOCK: 0
REDSTONE_COMPARATOR: 0
REDSTONE_COMPARATOR_OFF: 0
REDSTONE_COMPARATOR_ON: 0
REDSTONE_LAMP_OFF: 0
REDSTONE_LAMP_ON: 0
REDSTONE_ORE: 0
REDSTONE_TORCH_OFF: 0
REDSTONE_TORCH_ON: 0
REDSTONE_WIRE: 0
ROTTEN_FLESH: 0
SADDLE: 0
SAND: 0
SANDSTONE: 0
SANDSTONE_STAIRS: 0
SAPLING: 0
SEEDS: 0
SHEARS: 0
SIGN: 0
SIGN_POST: 0
SKULL: 0
SKULL_ITEM: 0
SLIME_BALL: 0
SMOOTH_BRICK: 0
SMOOTH_STAIRS: 0
SNOW: 0
SNOW_BALL: 0
SNOW_BLOCK: 0
SOIL: 0
SOUL_SAND: 0
SPECKLED_MELON: 0
SPIDER_EYE: 0
SPONGE: 0
SPRUCE_WOOD_STAIRS: 0
STAINED_CLAY: 0
STATIONARY_LAVA: 0
STATIONARY_WATER: 0
STEP: 0
STICK: 0
STONE: 0
STONE_AXE: 0
STONE_BUTTON: 0
STONE_HOE: 0
STONE_PICKAXE: 0
STONE_PLATE: 0
STONE_SPADE: 0
STONE_SWORD: 0
STORAGE_MINECART: 0
STRING: 0
SUGAR: 0
SUGAR_CANE: 0
SUGAR_CANE_BLOCK: 0
SULPHUR: 0
THIN_GLASS: 0
TNT: 0
TORCH: 0
TRAP_DOOR: 0
TRAPPED_CHEST: 0
TRIPWIRE: 0
TRIPWIRE_HOOK: 0
VINE: 0
WALL_SIGN: 0
WATCH: 0
WATER: 0
WATER_BUCKET: 0
WATER_LILY: 0
WEB: 0
WHEAT: 0
WOOD: 0
WOOD_AXE: 0
WOOD_BUTTON: 0
WOOD_DOOR: 0
WOOD_DOUBLE_STEP: 0
WOOD_HOE: 0
WOOD_PICKAXE: 0
WOOD_PLATE: 0
WOOD_SPADE: 0
WOOD_STAIRS: 0
WOOD_STEP: 0
WOOD_SWORD: 0
WOODEN_DOOR: 0
WOOL: 0
WORKBENCH: 0
WRITTEN_BOOK: 0
YELLOW_FLOWER: 0

Debug: false